##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hname", color = "(YW)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
desktop   = {icon = " ", name = "desktp", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(RD)"}
shell     = {icon = " ", name = "shell", color = "(MA)"}
packages  = {icon = " ", name = "packages", color = "(GN)"}
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
# memory    = {icon = " ", name = "memory", color = "(YW)"}
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0

[misc.figletLogos]
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode]
enable = false
path   = "/path/to/some/image.png" # Please use only absolute paths
scale  = 18
margin = [2, 2, 3,]
