[background]
cycle_timeout = 150
image = /home/bluebyt/Pictures/Wallpaper/Nord/Fox.png
preserve_aspect = false
randomize = false

[dock]
autohide_duration = 350
css_path =
dock_height = 64
icon_height = 48
autohide = false
position = bottom

icon_mapping_vesktop = /home/bluebyt/.config/dock-icons/discord.svg
icon_mapping_nwg-look = /home/bluebyt/.config/dock-icons/preferences-color.svg
icon_mapping_com.lite_xl.LiteXL = /home/bluebyt/.config/dock-icons/text-editor.svg
icon_mapping_pavucontrol = /home/bluebyt/.config/dock-icons/preferences-system.svg
icon_mapping_thunar = /home/bluebyt/.config/dock-icons/thunar.svg
icon_mapping_mpv = /home/bluebyt/.config/dock-icons/mpv.svg
icon_mapping_xfce4-terminal = /home/bluebyt/.config/dock-icons/terminal.svg
icon_mapping_brave-browser-beta = /home/bluebyt/.config/dock-icons/brave-dev.svg
icon_mapping_blueman-manager = /home/bluebyt/.config/dock-icons/bluetooth.svg
icon_mapping_org.xfce.ristretto = /home/bluebyt/.config/dock-icons/image-missing.svg
icon_mapping_firefox = /home/bluebyt/.config/dock-icons/firefox.svg
icon_mapping_org.keepassxc.KeePassXC = /home/bluebyt/.config/dock-icons/keepass.svg
icon_mapping_org.gnome.Nautilus = /home/bluebyt/.config/dock-icons/file-manager.svg
icon_mapping_org.wezfurlong.wezterm = /home/bluebyt/.config/dock-icons/wezterm.svg
icon_mapping_Alacritty = /home/bluebyt/.config/dock-icons/alacritty.svg
icon_mapping_chromium = /home/bluebyt/.config/dock-icons/chromium.svg
icon_mapping_net.nokyan.Resources = /home/bluebyt/.config/dock-icons/org.gnome.SystemMonitor.svg
icon_mapping_com.github.neithern.g4music = /home/bluebyt/.config/dock-icons/music-icon.svg
icon_mapping_io.github.amit9838.mousam = /home/bluebyt/.config/dock-icons/indicator-weather.svg
icon_mapping_org.pulseaudio.pavucontrol = /home/bluebyt/.config/dock-icons/systemsettings.svg
icon_mapping_org.gnome.TextEditor = /home/bluebyt/.config/dock-icons/basket.svg
icon_mapping_tilix = /home/bluebyt/.config/dock-icons/terminix.svg
icon_mapping_org.gnome.World.Secrets = /home/bluebyt/.config/dock-icons/keepass2.svg
icon_mapping_org.gnome.Loupe = /home/bluebyt/.config/dock-icons/accessories-image-viewer.svg
icon_mapping_org.gnome.SystemMonitor = /home/bluebyt/.config/dock-icons/utilities-system-monitor.svg
icon_mapping_foot = /home/bluebyt/.config/dock-icons/foot.svg
icon_mapping_better_control.py = /home/bluebyt/.config/dock-icons/system-settings.svg
icon_mapping_zen = /home/bluebyt/.config/dock-icons/web-browser.svg
icon_mapping_waypaper = /home/bluebyt/.config/dock-icons/desktop.svg
icon_mapping_brave = /home/bluebyt/.config/dock-icons/brave-dev.svg
icon_mapping_org.nickvision.tubeconverter = /home/bluebyt/.config/dock-icons/vidcutter.svg
icon_mapping_rio = /home/bluebyt/.config/dock-icons/terminal.svg
icon_mapping_com.mitchellh.ghostty = /home/bluebyt/.config/dock-icons/ghostwriter.svg
icon_mapping_helium = /home/bluebyt/.config/dock-icons/browser-tor.svg
icon_mapping_dev.zed.Zed = /home/bluebyt/.config/dock-icons/text.svg
icon_mapping_kitty = /home/bluebyt/.config/dock-icons/kitty.svg
icon_mapping_feh = /home/bluebyt/.config/dock-icons/kuickshow.svg

[panel]
autohide = false
autohide_duration = 300
# background_color =  rgba(0, 0, 0, 0.6)  #black; 60% opacity
background_color = 1a1b26FF
minimal_height = 48
clock_font = MesloLGS Nerd Font 12
clock_format = %e %a %H:%M
launchers_size = 24
launchers_spacing = 2
layer = top
position = bottom
menu_fuzzy_search = true
menu_icon =
menu_logout_command = wayland-logout
network_icon_invert_color = true
network_icon_size = 32
network_onclick_command = default
network_status = 0
network_status_font = MesloLGS Nerd Font 12
network_status_use_color = false
volume_display_timeout = 2.500000
widgets_left = menu workspace-switcher window-list
widgets_center = none
widgets_right = clock
live_window_previews = true
wp_quick_target_choice = default_sink # or default_source, or last_change
wp_popup_on_change = true
wp_popup_timeout = 2.5
wp_slider_length = 300
wp_scroll_sensitivity = 1
wp_invert_scroll = false
wp_icons_on_left = false
wp_spacing = 8
wp_left_click_action = show_mixer # uniquely, cannot be mute
wp_middle_click_action = mute_quick_target
wp_right_click_action = show_quick_target
wp_icon_size = 32

tray_smooth_scrolling_threshold = 5
tray_icon_size = 32
tray_menu_on_middle_click = false

notifications_autohide_timeout = 2.5
notifications_critical_in_dnd = true
notifications_icon_size = 32
commands_output_max_chars = 10

[workspace-switcher]
workspace_switcher_mode = "grid"
workspace_switcher_target_height = 128
workspace_switcher_render_views = true
