format = """
[](#ff5555)\
$username\
[](bg:#ffb86c fg:#ff5555)\
$directory\
[](fg:#ffb86c bg:#f1fa8c)\
$git_branch\
$git_status\
[](fg:#f1fa8c bg:#89b4fa)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#89b4fa bg:#89b4fa)\
$docker_context\
[](fg:#89b4fa bg:#89b4fa)\
$time\
[ ](fg:#89b4fa)\
"""

right_format = """
[](fg:#89b4fa)\
$cmd_duration\
[](fg:#89b4fa)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#ff5555 fg:#323232"
style_root = "bg:#ff5555"
format = '[$user ]($style)'

[directory]
style = "bg:#ffb86c fg:#323232"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f1fa8c fg:#323232"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f1fa8c fg:#323232"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#89b4fa fg:#323232"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#89b4fa fg:#323232"
format = '[ ♥ $time ]($style)'

[cmd_duration]
min_time = 0
min_time_to_notify = 2_000
style = "bg:#89b4fa fg:#323232"
format = '[  $duration ]($style)'
